version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - agro-datalake
    environment:
      - DISPLAY=${DISPLAY}
      - ENV=container
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/bin/google-chrome:/usr/bin/google-chrome
      - /usr/lib/google-chrome:/usr/lib/google-chrome
      - ${DOWNLOADS_PATH}:/app/downloads
      - ${IMAGENS_PATH}:/app/imagens
    privileged: true
    stdin_open: true 
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agro-datalake

volumes:
  mongodb_data:

networks:
  agro-datalake:
    driver: bridge

    